project_id = "rtvrdbbojqsrbkngnjgq"

[functions.send-contact-email]
verify_jwt = false

[functions.fetch-auto-news]
verify_jwt = false

[functions.phone-verification]
verify_jwt = true

[functions.send-scholarship-alerts]
verify_jwt = false

[functions.send-registration-status-email]
verify_jwt = false

[functions.send-admin-invite]
verify_jwt = true
